export const ENVS = {
  DATABASE_TYPE: 'DATABASE_TYPE',
  POSTGRES_HOST: 'POSTGRES_HOST',
  POSTGRES_PORT: 'POSTGRES_PORT',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DB: 'POSTGRES_DB',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_HOST: 'REDIS_HOST',
  EMAIL: 'EMAIL',
  EMAIL_PASSWORD: 'EMAIL_PASSWORD',
};
