export const HASH_SERVICE_TOKEN = Symbol('HASH_SERVICE_TOKEN');
export const GENERATOR_SERVICE_TOKEN = Symbol('GENERATOR_SERVICE_TOKEN');
export const TOKENS_SERVICE_TOKEN = Symbol('TOKENS_SERVICE_TOKEN');
