export const BOOKS_READ_TRACKING_REPOSITORY_TOKEN = Symbol(
  'BOOKS_READ_TRACKING_REPOSITORY_TOKEN',
);

export const PAGES_READ_TRACKING_REPOSITORY_TOKEN = Symbol(
  'PAGE_READ_TRACKING_REPOSITORY_TOKEN',
);
