export * from './pages-repository.interface';
export * from './page.interface';
export * from './save-page-credentials.interface';
export * from './find-pages-credentials.interface';
export * from './update-page-credentials.interface';
export * from './delete-page-credentials.interface';
export * from './create-page-credentials.interface';
export * from './verify-page-ids-in-book-credentials.interface';
export * from './verify-page-ids-function-response.interface';
